# SwiftLint Configuration for Claude Code Projects

disabled_rules:
  - trailing_whitespace  # Handled by swift-format
  - vertical_whitespace  # Handled by swift-format

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule Configuration
line_length: 120
type_body_length: 300
function_body_length: 60
cyclomatic_complexity: 10
file_length: 500

# Naming Rules
type_name:
  min_length: 3
  max_length: 40
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z

# Force Cast/Try Rules
force_cast: warning
force_try: warning
force_unwrapping: warning

# Excluded Paths
excluded:
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - Package.swift
  - "**/Generated"
  - "**/Derived"

# Included File Extensions
included:
  - ".swift"

# Reporter
reporter: "xcode"
