#!/bin/bash
echo "🔍 Performance Test Helper"
echo ""
echo "📱 Run the app in Xcode and:"
echo "   1. Open Debug Navigator (⌘+7)"
echo "   2. Click 'Memory' gauge"
echo "   3. Open Scenes tab in app"
echo "   4. Scroll through scenes for 30 seconds"
echo ""
echo "✅ GOOD: Memory stays 100-150 MB"
echo "❌ BAD:  Memory climbs to 300+ MB"
echo ""
echo "Cache directory location:"
ls -lh ~/Library/Caches/ImageCache 2>/dev/null || echo "No cache yet - run the app first!"
echo ""
echo "Image count in cache:"
find ~/Library/Caches/ImageCache -type f 2>/dev/null | wc -l | xargs echo "Cached images:"
